<?php

use Illuminate\Database\Seeder;

class ProvincesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('provinces')->insert(['province' => 'Aceh']);
        DB::table('provinces')->insert(['province' => 'Sumatera Utara']);
        DB::table('provinces')->insert(['province' => 'Sumatera Barat']);
        DB::table('provinces')->insert(['province' => 'Riau']);
        DB::table('provinces')->insert(['province' => 'Jambi']);
        DB::table('provinces')->insert(['province' => 'Sumatera Selatan']);
        DB::table('provinces')->insert(['province' => 'Bengkulu']);
        DB::table('provinces')->insert(['province' => 'Lampung']);
        DB::table('provinces')->insert(['province' => 'Kepulauan Bangka Belitung']);
        DB::table('provinces')->insert(['province' => 'Kepulauan Riau']);

        DB::table('provinces')->insert(['province' => 'DKI Jakarta']);
        DB::table('provinces')->insert(['province' => 'Jawa Barat']);
        DB::table('provinces')->insert(['province' => 'Jawa Tengah']);
        DB::table('provinces')->insert(['province' => 'Yogyakarta']);
        DB::table('provinces')->insert(['province' => 'Jawa Timur']);
        DB::table('provinces')->insert(['province' => 'Banten']);
        DB::table('provinces')->insert(['province' => 'Bali']);
        DB::table('provinces')->insert(['province' => 'Nusa Tenggara Barat']);
        DB::table('provinces')->insert(['province' => 'Nusa Tenggara Timur']);
        DB::table('provinces')->insert(['province' => 'Kalimantan Barat']);

        DB::table('provinces')->insert(['province' => 'Kalimantan Tengah']);
        DB::table('provinces')->insert(['province' => 'Kalimantan Selatan']);
        DB::table('provinces')->insert(['province' => 'Kalimantan Timur']);
        DB::table('provinces')->insert(['province' => 'Kalimantan Utara']);
        DB::table('provinces')->insert(['province' => 'Sulawesi Utara']);
        DB::table('provinces')->insert(['province' => 'Sulawesi Tengah']);
        DB::table('provinces')->insert(['province' => 'Sulawesi Selatan']);
        DB::table('provinces')->insert(['province' => 'Sulawesi Tenggara']);
        DB::table('provinces')->insert(['province' => 'Gorontalo']);
        DB::table('provinces')->insert(['province' => 'Sulawesi Barat']);
        
        DB::table('provinces')->insert(['province' => 'Maluku']);
        DB::table('provinces')->insert(['province' => 'Maluku Utara']);
        DB::table('provinces')->insert(['province' => 'Papua Barat']);
        DB::table('provinces')->insert(['province' => 'Papua']);

        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Simeulue']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Singkil']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Selatan']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Tenggara']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Timur']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Tengah']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Barat']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Besar']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Pidie']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Bireuen']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Utara']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Barat Daya']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Gayo Lues']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Tamiang']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Nagan Raya']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Aceh Jaya']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Bener Meriah']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Pidie Jaya']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Banda Aceh']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Sabang']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Langsa']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Lhokseumawe']);
        DB::table('cities')->insert(['province_id' => '1', 'city' => 'Subulussalam']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Nias']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Mandailing Natal']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Tapanuli Selatan']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Tapanuli Tengah']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Tapanuli Utara']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Toba Samosir']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Labuhan Batu']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Asahan']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Simalungun']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Dairi']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Karo']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Deli Serdang']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Langkat']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Nias Selatan']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Humbang Hasundutan']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Pakpak Bharat']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Samosir']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Serdang Bedagai']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Batu Bara']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Padang Lawas Utara']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Padang Lawas']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Labuhan Batu Selatan']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Labuhan Batu Utara']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Nias Utara']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Nias Barat']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Sibolga']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Tanjung Balai']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Pematang Siantar']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Tebing Tinggi']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Medan']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Binjai']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Padangsidimpuan']);
        DB::table('cities')->insert(['province_id' => '2', 'city' => 'Gunungsitoli']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Kepulauan Mentawai']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Pesisir Selatan']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Solok']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Sijunjung']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Tanah Datar']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Padang Pariaman']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Agam']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Lima Puluh Kota']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Pasaman']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Solok Selatan']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Dharmasraya']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Pasaman Barat']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Padang']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Solok']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Sawah Lunto']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Padang Panjang']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Bukittinggi']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Payakumbuh']);
        DB::table('cities')->insert(['province_id' => '3', 'city' => 'Pariaman']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Kuantan Singingi']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Indragiri Hulu']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Indragiri Hilir']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Pelalawan']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Siak']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Kampar']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Rokan Hulu']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Bengkalis']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Rokan Hilir']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Kepulauan Meranti']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Pekanbaru']);
        DB::table('cities')->insert(['province_id' => '4', 'city' => 'Dumai']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Kerinci']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Merangin']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Sarolangun']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Batang Hari']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Muaro Jambi']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Tanjung Jabung Timur']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Tanjung Jabung Barat']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Tebo']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Bungo']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Jambi']);
        DB::table('cities')->insert(['province_id' => '5', 'city' => 'Sungai Penuh']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Ogan Komering Ulu']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Ogan Komering Ilir']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Muara Enim']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Lahat']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Musi Rawas']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Musi Banyuasin']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Banyu Asin']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Ogan Komering Ulu Selatan']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Ogan Komering Ulu Timur']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Ogan Ilir']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Empat Lawang']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Penukal Abab Lematang Ilir']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Musi Rawas Utara']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Palembang']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Prabumulih']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Pagar Alam']);
        DB::table('cities')->insert(['province_id' => '6', 'city' => 'Lubuklinggau']);
        DB::table('cities')->insert(['province_id' => '7', 'city' => 'Bengkulu Selatan']);
        DB::table('cities')->insert(['province_id' => '7', 'city' => 'Rejang Lebong']);
        DB::table('cities')->insert(['province_id' => '7', 'city' => 'Bengkulu Utara']);
        DB::table('cities')->insert(['province_id' => '7', 'city' => 'Kaur']);
        DB::table('cities')->insert(['province_id' => '7', 'city' => 'Seluma']);
        DB::table('cities')->insert(['province_id' => '7', 'city' => 'Mukomuko']);
        DB::table('cities')->insert(['province_id' => '7', 'city' => 'Lebong']);
        DB::table('cities')->insert(['province_id' => '7', 'city' => 'Kepahiang']);
        DB::table('cities')->insert(['province_id' => '7', 'city' => 'Bengkulu Tengah']);
        DB::table('cities')->insert(['province_id' => '7', 'city' => 'Bengkulu']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Lampung Barat']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Tanggamus']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Lampung Selatan']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Lampung Timur']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Lampung Tengah']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Lampung Utara']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Way Kanan']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Tulangbawang']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Pesawaran']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Pringsewu']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Mesuji']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Tulang Bawang Barat']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Pesisir Barat']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Bandar Lampung']);
        DB::table('cities')->insert(['province_id' => '8', 'city' => 'Metro']);
        DB::table('cities')->insert(['province_id' => '9', 'city' => 'Bangka']);
        DB::table('cities')->insert(['province_id' => '9', 'city' => 'Belitung']);
        DB::table('cities')->insert(['province_id' => '9', 'city' => 'Bangka Barat']);
        DB::table('cities')->insert(['province_id' => '9', 'city' => 'Bangka Tengah']);
        DB::table('cities')->insert(['province_id' => '9', 'city' => 'Bangka Selatan']);
        DB::table('cities')->insert(['province_id' => '9', 'city' => 'Belitung Timur']);
        DB::table('cities')->insert(['province_id' => '9', 'city' => 'Pangkal Pinang']);
        DB::table('cities')->insert(['province_id' => '10', 'city' => 'Karimun']);
        DB::table('cities')->insert(['province_id' => '10', 'city' => 'Bintan']);
        DB::table('cities')->insert(['province_id' => '10', 'city' => 'Natuna']);
        DB::table('cities')->insert(['province_id' => '10', 'city' => 'Lingga']);
        DB::table('cities')->insert(['province_id' => '10', 'city' => 'Kepulauan Anambas']);
        DB::table('cities')->insert(['province_id' => '10', 'city' => 'Batam']);
        DB::table('cities')->insert(['province_id' => '10', 'city' => 'Tanjung Pinang']);
        DB::table('cities')->insert(['province_id' => '11', 'city' => 'Kepulauan Seribu']);
        DB::table('cities')->insert(['province_id' => '11', 'city' => 'Jakarta Selatan']);
        DB::table('cities')->insert(['province_id' => '11', 'city' => 'Jakarta Timur']);
        DB::table('cities')->insert(['province_id' => '11', 'city' => 'Jakarta Pusat']);
        DB::table('cities')->insert(['province_id' => '11', 'city' => 'Jakarta Barat']);
        DB::table('cities')->insert(['province_id' => '11', 'city' => 'Jakarta Utara']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Bogor']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Sukabumi']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Cianjur']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Garut']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Tasikmalaya']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Ciamis']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Kuningan']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Cirebon']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Majalengka']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Sumedang']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Indramayu']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Subang']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Purwakarta']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Karawang']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Bekasi']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Bandung Barat']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Pangandaran']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Bogor']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Sukabumi']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Bandung']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Cirebon']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Bekasi']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Depok']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Cimahi']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Tasikmalaya']);
        DB::table('cities')->insert(['province_id' => '12', 'city' => 'Banjar']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Cilacap']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Banyumas']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Purbalingga']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Banjarnegara']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Kebumen']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Purworejo']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Wonosobo']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Magelang']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Boyolali']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Klaten']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Sukoharjo']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Wonogiri']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Karanganyar']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Sragen']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Grobogan']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Blora']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Rembang']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Pati']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Kudus']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Jepara']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Demak']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Semarang']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Temanggung']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Kendal']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Batang']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Pekalongan']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Pemalang']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Tegal']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Brebes']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Magelang']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Surakarta']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Salatiga']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Semarang']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Pekalongan']);
        DB::table('cities')->insert(['province_id' => '13', 'city' => 'Tegal']);
        DB::table('cities')->insert(['province_id' => '14', 'city' => 'Kulon Progo']);
        DB::table('cities')->insert(['province_id' => '14', 'city' => 'Bantul']);
        DB::table('cities')->insert(['province_id' => '14', 'city' => 'Gunung Kidul']);
        DB::table('cities')->insert(['province_id' => '14', 'city' => 'Sleman']);
        DB::table('cities')->insert(['province_id' => '14', 'city' => 'Yogyakarta']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Pacitan']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Ponorogo']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Trenggalek']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Tulungagung']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Blitar']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Kediri']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Malang']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Lumajang']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Jember']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Banyuwangi']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Bondowoso']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Situbondo']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Probolinggo']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Pasuruan']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Sidoarjo']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Mojokerto']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Jombang']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Nganjuk']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Madiun']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Magetan']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Ngawi']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Bojonegoro']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Tuban']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Lamongan']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Gresik']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Bangkalan']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Sampang']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Pamekasan']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Sumenep']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Kediri']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Blitar']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Malang']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Probolinggo']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Pasuruan']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Mojokerto']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Madiun']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Surabaya']);
        DB::table('cities')->insert(['province_id' => '15', 'city' => 'Batu']);
        DB::table('cities')->insert(['province_id' => '16', 'city' => 'Pandeglang']);
        DB::table('cities')->insert(['province_id' => '16', 'city' => 'Lebak']);
        DB::table('cities')->insert(['province_id' => '16', 'city' => 'Tangerang']);
        DB::table('cities')->insert(['province_id' => '16', 'city' => 'Serang']);
        DB::table('cities')->insert(['province_id' => '16', 'city' => 'Tangerang']);
        DB::table('cities')->insert(['province_id' => '16', 'city' => 'Cilegon']);
        DB::table('cities')->insert(['province_id' => '16', 'city' => 'Serang']);
        DB::table('cities')->insert(['province_id' => '16', 'city' => 'Tangerang Selatan']);
        DB::table('cities')->insert(['province_id' => '17', 'city' => 'Jembrana']);
        DB::table('cities')->insert(['province_id' => '17', 'city' => 'Tabanan']);
        DB::table('cities')->insert(['province_id' => '17', 'city' => 'Badung']);
        DB::table('cities')->insert(['province_id' => '17', 'city' => 'Gianyar']);
        DB::table('cities')->insert(['province_id' => '17', 'city' => 'Klungkung']);
        DB::table('cities')->insert(['province_id' => '17', 'city' => 'Bangli']);
        DB::table('cities')->insert(['province_id' => '17', 'city' => 'Karang Asem']);
        DB::table('cities')->insert(['province_id' => '17', 'city' => 'Buleleng']);
        DB::table('cities')->insert(['province_id' => '17', 'city' => 'Denpasar']);
        DB::table('cities')->insert(['province_id' => '18', 'city' => 'Lombok Barat']);
        DB::table('cities')->insert(['province_id' => '18', 'city' => 'Lombok Tengah']);
        DB::table('cities')->insert(['province_id' => '18', 'city' => 'Lombok Timur']);
        DB::table('cities')->insert(['province_id' => '18', 'city' => 'Sumbawa']);
        DB::table('cities')->insert(['province_id' => '18', 'city' => 'Dompu']);
        DB::table('cities')->insert(['province_id' => '18', 'city' => 'Bima']);
        DB::table('cities')->insert(['province_id' => '18', 'city' => 'Sumbawa Barat']);
        DB::table('cities')->insert(['province_id' => '18', 'city' => 'Lombok Utara']);
        DB::table('cities')->insert(['province_id' => '18', 'city' => 'Mataram']);
        DB::table('cities')->insert(['province_id' => '18', 'city' => 'Bima']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Sumba Barat']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Sumba Timur']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Kupang']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Timor Tengah Selatan']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Timor Tengah Utara']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Belu']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Alor']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Lembata']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Flores Timur']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Sikka']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Ende']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Ngada']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Manggarai']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Rote Ndao']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Manggarai Barat']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Sumba Tengah']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Sumba Barat Daya']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Nagekeo']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Manggarai Timur']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Sabu Raijua']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Malaka']);
        DB::table('cities')->insert(['province_id' => '19', 'city' => 'Kupang']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Sambas']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Bengkayang']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Landak']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Mempawah']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Sanggau']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Ketapang']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Sintang']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Kapuas Hulu']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Sekadau']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Melawi']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Kayong Utara']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Kubu Raya']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Pontianak']);
        DB::table('cities')->insert(['province_id' => '20', 'city' => 'Singkawang']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Kotawaringin Barat']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Kotawaringin Timur']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Kapuas']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Barito Selatan']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Barito Utara']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Sukamara']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Lamandau']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Seruyan']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Katingan']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Pulang Pisau']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Gunung Mas']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Barito Timur']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Murung Raya']);
        DB::table('cities')->insert(['province_id' => '21', 'city' => 'Palangka Raya']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Tanah Laut']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Baru']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Banjar']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Barito Kuala']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Tapin']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Hulu Sungai Selatan']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Hulu Sungai Tengah']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Hulu Sungai Utara']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Tabalong']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Tanah Bumbu']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Balangan']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Banjarmasin']);
        DB::table('cities')->insert(['province_id' => '22', 'city' => 'Banjar Baru']);
        DB::table('cities')->insert(['province_id' => '23', 'city' => 'Paser']);
        DB::table('cities')->insert(['province_id' => '23', 'city' => 'Kutai Barat']);
        DB::table('cities')->insert(['province_id' => '23', 'city' => 'Kutai Kartanegara']);
        DB::table('cities')->insert(['province_id' => '23', 'city' => 'Kutai Timur']);
        DB::table('cities')->insert(['province_id' => '23', 'city' => 'Berau']);
        DB::table('cities')->insert(['province_id' => '23', 'city' => 'Penajam Paser Utara']);
        DB::table('cities')->insert(['province_id' => '23', 'city' => 'Mahakam Hulu']);
        DB::table('cities')->insert(['province_id' => '23', 'city' => 'Balikpapan']);
        DB::table('cities')->insert(['province_id' => '23', 'city' => 'Samarinda']);
        DB::table('cities')->insert(['province_id' => '23', 'city' => 'Bontang']);
        DB::table('cities')->insert(['province_id' => '24', 'city' => 'Malinau']);
        DB::table('cities')->insert(['province_id' => '24', 'city' => 'Bulungan']);
        DB::table('cities')->insert(['province_id' => '24', 'city' => 'Tana Tidung']);
        DB::table('cities')->insert(['province_id' => '24', 'city' => 'Nunukan']);
        DB::table('cities')->insert(['province_id' => '24', 'city' => 'Tarakan']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Bolaang Mongondow']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Minahasa']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Kepulauan Sangihe']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Kepulauan Talaud']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Minahasa Selatan']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Minahasa Utara']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Bolaang Mongondow Utara']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Siau Tagulandang Biaro']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Minahasa Tenggara']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Bolaang Mongondow Selatan']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Bolaang Mongondow Timur']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Manado']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Bitung']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Tomohon']);
        DB::table('cities')->insert(['province_id' => '25', 'city' => 'Kotamobagu']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Banggai Kepulauan']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Banggai']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Morowali']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Poso']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Donggala']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Toli-toli']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Buol']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Parigi Moutong']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Tojo Una-una']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Sigi']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Banggai Laut']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Morowali Utara']);
        DB::table('cities')->insert(['province_id' => '26', 'city' => 'Palu']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Kepulauan Selayar']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Bulukumba']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Bantaeng']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Jeneponto']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Takalar']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Gowa']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Sinjai']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Maros']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Pangkajene Dan Kepulauan']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Barru']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Bone']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Soppeng']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Wajo']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Sidenreng Rappang']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Pinrang']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Enrekang']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Luwu']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Tana Toraja']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Luwu Utara']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Luwu Timur']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Toraja Utara']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Makassar']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Parepare']);
        DB::table('cities')->insert(['province_id' => '27', 'city' => 'Palopo']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Buton']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Muna']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Konawe']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Kolaka']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Konawe Selatan']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Bombana']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Wakatobi']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Kolaka Utara']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Buton Utara']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Konawe Utara']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Kolaka Timur']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Konawe Kepulauan']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Muna Barat']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Buton Tengah']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Buton Selatan']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Kendari']);
        DB::table('cities')->insert(['province_id' => '28', 'city' => 'Baubau']);
        DB::table('cities')->insert(['province_id' => '29', 'city' => 'Boalemo']);
        DB::table('cities')->insert(['province_id' => '29', 'city' => 'Gorontalo']);
        DB::table('cities')->insert(['province_id' => '29', 'city' => 'Pohuwato']);
        DB::table('cities')->insert(['province_id' => '29', 'city' => 'Bone Bolango']);
        DB::table('cities')->insert(['province_id' => '29', 'city' => 'Gorontalo Utara']);
        DB::table('cities')->insert(['province_id' => '29', 'city' => 'Gorontalo']);
        DB::table('cities')->insert(['province_id' => '30', 'city' => 'Majene']);
        DB::table('cities')->insert(['province_id' => '30', 'city' => 'Polewali Mandar']);
        DB::table('cities')->insert(['province_id' => '30', 'city' => 'Mamasa']);
        DB::table('cities')->insert(['province_id' => '30', 'city' => 'Mamuju']);
        DB::table('cities')->insert(['province_id' => '30', 'city' => 'Mamuju Utara']);
        DB::table('cities')->insert(['province_id' => '30', 'city' => 'Mamuju Tengah']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Maluku Tenggara Barat']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Maluku Tenggara']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Maluku Tengah']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Buru']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Kepulauan Aru']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Seram Bagian Barat']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Seram Bagian Timur']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Maluku Barat Daya']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Buru Selatan']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Ambon']);
        DB::table('cities')->insert(['province_id' => '31', 'city' => 'Tual']);
        DB::table('cities')->insert(['province_id' => '32', 'city' => 'Halmahera Barat']);
        DB::table('cities')->insert(['province_id' => '32', 'city' => 'Halmahera Tengah']);
        DB::table('cities')->insert(['province_id' => '32', 'city' => 'Kepulauan Sula']);
        DB::table('cities')->insert(['province_id' => '32', 'city' => 'Halmahera Selatan']);
        DB::table('cities')->insert(['province_id' => '32', 'city' => 'Halmahera Utara']);
        DB::table('cities')->insert(['province_id' => '32', 'city' => 'Halmahera Timur']);
        DB::table('cities')->insert(['province_id' => '32', 'city' => 'Pulau Morotai']);
        DB::table('cities')->insert(['province_id' => '32', 'city' => 'Pulau Taliabu']);
        DB::table('cities')->insert(['province_id' => '32', 'city' => 'Ternate']);
        DB::table('cities')->insert(['province_id' => '32', 'city' => 'Tidore Kepulauan']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Fakfak']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Kaimana']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Teluk Wondama']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Teluk Bintuni']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Manokwari']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Sorong Selatan']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Sorong']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Raja Ampat']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Tambrauw']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Maybrat']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Manokwari Selatan']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Pegunungan Arfak']);
        DB::table('cities')->insert(['province_id' => '33', 'city' => 'Sorong']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Merauke']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Jayawijaya']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Jayapura']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Nabire']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Kepulauan Yapen']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Biak Numfor']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Paniai']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Puncak Jaya']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Mimika']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Boven Digoel']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Mappi']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Asmat']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Yahukimo']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Pegunungan Bintang']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Tolikara']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Sarmi']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Keerom']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Waropen']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Supiori']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Mamberamo Raya']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Nduga']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Lanny Jaya']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Mamberamo Tengah']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Yalimo']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Puncak']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Dogiyai']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Intan Jaya']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Deiyai']);
        DB::table('cities')->insert(['province_id' => '34', 'city' => 'Jayapura']);
    }
}
